//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISALMINTWebSystemNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public string Codigo { get; set; }
        public string Nombre { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public string Distribuidor { get; set; }
        public double PrecioCompra { get; set; }
        public int CantidadIngresada { get; set; }
        public string FallaFabrica { get; set; }
        public string Estado { get; set; }
        public int TipoId { get; set; }
    
        public virtual Tipo Tipo { get; set; }
    }
}
